apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-pod
  namespace: service-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
      # service-api container configuration
      - name: service-api
        resources:
          limits:
            cpu: "2000m" # Up to 2 full cores
          requests:
            cpu: "1000m" # Use 1 full cores
