apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/sales-pod/
patchesStrategicMerge:
- ./kind-sales-patch.yaml
images:
- name: sales-api-image
  newName: sales-api-amd64
  newTag: "1.0"
